apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-cors
data:
  cors.json: |
    {
      "CORSRules": [
        {
          "AllowedOrigins": ["*"],
          "AllowedMethods": ["GET", "PUT", "POST", "DELETE"],
          "AllowedHeaders": ["*"],
          "ExposeHeaders": ["ETag"]
        }
      ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
      nodePort: 31566
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "s3"
            - name: DEBUG
              value: "1"
            - name: LOCALSTACK_VOLUME_DIR
              value: "/tmp/localstack-data"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
          volumeMounts:
            - name: localstack-vol
              mountPath: /tmp/localstack-data
            - name: cors-config
              mountPath: /tmp/cors.json
              subPath: cors.json
      volumes:
        - name: localstack-vol
          emptyDir: {}
        - name: cors-config
          configMap:
            name: localstack-cors