{{- if .Values.mlflow.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mlflow-data
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.mlflow.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.mlflow.persistence.size }}
{{- end }}